### ISSUE TITLE
epics base-7.xx compile issue

### ISSUE THREAD

**Issue by kimanha** [mdavidsaver/pscdrv#2]
Hi Michael,

I tried to compile pscDrv for epics 7.x and find compile issue. 
My linux is Ubuntu 18.4.

make[2]: Entering directory '/home/kha/epics/pscdrv/testApp/O.linux-x86_64-debug'
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET   -D_X86_64_  -DUNIX  -Dlinux     -g   -Wall      -mtune=generic      -m64  -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/gcc -I../../include/os/Linux -I../../include -I/home/kha/epics/base-7.0.3.1/include/compiler/gcc -I/home/kha/epics/base-7.0.3.1/include/os/Linux -I/home/kha/epics/base-7.0.3.1/include        -MM -MF testValues.d  ../testValues.cpp
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET   -D_X86_64_  -DUNIX  -Dlinux     -g   -Wall      -mtune=generic      -m64  -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/gcc -I../../include/os/Linux -I../../include -I/home/kha/epics/base-7.0.3.1/include/compiler/gcc -I/home/kha/epics/base-7.0.3.1/include/os/Linux -I/home/kha/epics/base-7.0.3.1/include        -c ../testValues.cpp
make[2]: *** No rule to make target '../../lib/linux-x86_64-debug/libCom.a', needed by 'testValues'.  Stop.
make[2]: Leaving directory '/home/kha/epics/pscdrv/testApp/O.linux-x86_64-debug'
/home/kha/epics/base-7.0.3.1/configure/RULES_ARCHS:58: recipe for target 'install.linux-x86_64-debug' failed
make[1]: *** [install.linux-x86_64-debug] Error 2
make[1]: Leaving directory '/home/kha/epics/pscdrv/testApp'
/home/kha/epics/base-7.0.3.1/configure/RULES_DIRS:84: recipe for target 'testApp.install' failed
make: *** [testApp.install] Error 2

**Comment by shengb** [comment]
@kimanha I compiled this driver on RHEL7 with EPICS R7.0.3. From the error message, it seems that you don't have linux-x86_64-debug ARCH compiled in your base, but you have the debug enabled when compiling this IOC application.
